name: authpass
description: Password Manager with support for kdbx 3.x and 4.x

version: 1.7.8+147

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #  kdbx: ^0.2.0
  kdbx:
    path: ../deps/kdbx.dart
  argon2_ffi:
    git:
      url: https://github.com/authpass/argon2_ffi.git
      ref: 6c798276436f96315f34c717a6c0b8d94de45255
  simple_form_field_validator:
    git:
      url: https://github.com/hpoul/flutter_utils.git
      path: packages/simple_form_field_validator
      ref: 4c65f09005a1086525ebe2ae004eccdc2dd56fe1
  logging: '>=0.11.3+2 <1.0.0'
  logging_appenders: ^0.4.2+5
  diac_client:
    path: ../deps/diac/diac_client

  synchronized: ^2.2.0+2
#  file_picker: ^1.6.2
  file_picker_writable: ^1.2.0-dev.2
  #  file_picker_writable:
#    path: /Users/herbert/dev/file_picker_writable
#  file_picker_writable:
#    git:
#      url: https://github.com/hpoul/file_picker_writable.git
#      ref: fc45c929361d9ace37e5f7b2fae756b98e85b223
  json_annotation: ^3.0.1
  freezed_annotation: ^0.11.0+1
  built_value: ^7.1.0
  simple_json_persistence: ^1.0.2
  provider: ^4.3.2+1
  http: ^0.12.2
  meta: '>=1.0.0 <2.0.0'
  clock: ^1.0.1
  intl: ^0.16.1
  path: ^1.7.0
  isolate: ^2.0.3
#  clipboard_manager: ^0.0.4

  flutter_async_utils: ^0.1.0
  flutter_svg: ">=0.18.1 <1.0.0"
  #usage: ^3.4.1
  usage:
    git:
      url: https://github.com/hpoul/usage.git
      ref: custom-user-agent
  package_info: ^0.4.3
#  package_info: ^0.4.0+13
#  package_info_macos:
#    git:
#      url: https://github.com/authpass/package_info_macos.git
##    path: ../deps/package_info_macos
  device_info: ^0.4.2+7
  path_provider: ^1.6.14
  path_provider_macos: ^0.0.4+3
  path_provider_linux: ">=0.0.1 <2.0.0"
  #path_provider_windows: '>=0.0.1+2 <2.0.0'
  analytics_event: ^0.1.2
  autofill_service:
    path: ../deps/autofill_service

  flutter_colorpicker: ^0.3.4
  flutter_speed_dial: ^1.2.5
  flutter_email_sender: ^3.0.1
  flutter_store_listing: ^0.1.1+2

  biometric_storage: ^1.0.1+5
#  biometric_storage:
#    path: ../deps/biometric_storage
  uuid: ^2.2.2
  url_launcher: ^5.5.0
  font_awesome_flutter: ^8.8.1
  otp: ^2.2.3
  zxcvbn: ^0.0.1


  # UI Utilities and Widgets
  badges: ^1.1.1
  qr_flutter: ^3.2.0
  flushbar: ^1.10.4
  filesystem_picker: ^1.0.2

  # (Small) utility packages
  quiver: ">=2.0.0 <3.0.0"
  tuple: ^1.0.3
  rxdart: ^0.24.1
  charcode: ^1.1.3
  recase: ^3.0.0
  # collection utilities:
  flinq: ^1.1.1

  string_literal_finder_annotations: ^0.1.1+1

  # WebDAV
#  http_auth: ^0.2.9
  http_auth:
    git:
      url: https://github.com/authpass/http_auth.git
      ref: 37b04ada13436195abaa12433ceb18535a4d4d45

  # google drive
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12

  # dropbox
  #oauth2: ^1.3.0
  oauth2:
    #path: /Users/herbert/dev/patches/oauth2
    git:
      url: https://github.com/authpass/oauth2.git
      ref: 508e542284733bbf0e0515d8ef0bbb5d39d47021

  # FDE
  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 1feed8db2e5222af4e5d8495ac45135a2701c755
#      ref: android-dummy-plugin
#      url: https://github.com/google/flutter-desktop-embedding.git
#      path: plugins/file_chooser
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: 1feed8db2e5222af4e5d8495ac45135a2701c755
  # Used for windows, for now:
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: 1feed8db2e5222af4e5d8495ac45135a2701c755

  macos_secure_bookmarks: ^0.1.2

  # UI Utils
  percent_indicator: ^2.1.5

  # Plugins
  #flutter_barcode_scanner: ^0.1.7
#  barcode_scan: ^3.0.1 <-- not working (protobuf damnit)
  barcode_scan:
    git:
      url: https://github.com/RohitKumarMishra/flutter_barcode_reader.git
      ref: 85cfc7efee91c3444d24435486cf292a32f04499
  open_file: ^3.0.1
  esys_flutter_share: ^1.0.2
  flutter_windowmanager: ^0.0.2

  mime: ^0.9.7
  pedantic: ^1.9.2
  ffi: ^0.1.3
  # AuthPass Cloud email deps
  enough_mail: ^0.0.32
  flutter_html: ^1.0.2
  flutter_linkify: ^3.1.3
  openapi_base: ^0.1.5+3
  flutter_cache_manager: ^1.4.1
  cached_network_image: ^2.2.0+1
  authpass_cloud_shared:
    path: ../deps/authpass-cloud/packages/authpass_cloud_shared
  # windows updater
  winsparkle_flutter:
    git:
      url: https://github.com/authpass/winsparkle_flutter.git
      ref: 2c56009666a2a8b6802a87a87e5135ed724edfc2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.2
#   https://github.com/flutter/flutter/issues/62240
#  analyzer: ^0.39.17
  json_serializable: ^3.4.0
  build_runner: ^1.10.2
  builder_static_text: ^0.0.1+2
  built_value_generator: ^7.1.0
  analytics_event_gen: ^0.1.2
  freezed: ^0.11.5
  plugin_platform_interface: ^1.0.2

dependency_overrides:
#  pedantic: ^1.9.2
#  build_runner: ^1.10.2
#  xml: '>=3.7.0 <4.0.0'
#  petitparser: '>=3.0.0 <4.0.0'
  kdbx:
    path: ../deps/kdbx.dart
  pointycastle:
    git:
      url: https://github.com/authpass/pointycastle.git
      ref: 73dea5d9d441da30bd2c99adc16e5bf98d6c2a43
  # The following two are required since flutter 1.21
  # but blocked by e.g flutter_cache_manager
  file: ^6.0.0-nullsafety.1
  process: ^4.0.0-nullsafety.1


#  openapi_base:
#    path: /Users/herbert/dev/authpass-cloud/deps/openapi_dart/packages/openapi_base

#  url_launcher_fde:
#    path: /Users/herbert/dev/flutter/flutter-desktop-embedding/plugins/flutter_plugins/url_launcher_fde
#  file_chooser:
#    path: /Users/herbert/dev/flutter/flutter-desktop-embedding/plugins/file_chooser
#  biometric_storage:
#    path: ../deps/biometric_storage
#  macos_secure_bookmarks:
#    path: /Users/herbert/dev/macos_secure_bookmarks


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/jetbrains/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/jetbrains/JetBrainsMono-Bold.ttf
          weight: 700
