on:
  push:
    branches:
      - main
      - 'linux**'
  pull_request:
name: linux_flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: authpass.flatpak
        manifest-path: flatpak/app.authpass.AuthPass.yaml
        cache-key: flatpak-builder-${{ github.sha }}
    - uses: actions/upload-artifact@v3
      with:
        name: authpass.flatpak
        path: authpass.flatpak
        if-no-files-found: error
