name: unit test with coverage

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      webdav:
        # Docker Hub image
        image: bytemark/webdav
        ports:
          - "10280:80"
        env:
          AUTH_TYPE: Digest
          USERNAME: authpass
          PASSWORD: authpa55

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: ci-install-deps
        run: "./authpass/_tools/ci-install-deps.sh android"
      - name: Postdeploy
        env:
          BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
        run: authpass/_tools/postdeploy.sh
      - run: authpass/_tools/test-coverage.sh
      - name: Coveralls
        uses: coverallsapp/github-action@master
        env:
          COVERALLS_FLAG_NAME: Unit
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: authpass/coverage/lcov.info
          base-path: authpass
